---
galaxy_info:
  role_name: patching
  author: Ali Muhammad
  description: Ubuntu system patching.
  company: CTAC
  license: GPLv3
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies: []
