---
- name: Harden and provision Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure UFW is installed and enabled
      apt: name=ufw state=present

    - name: Allow SSH and HTTP
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

