name: Build CIS-Hardened Ubuntu AMI

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-ami:
    name: Build AMI with Packer + Ansible
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Packer
      uses: hashicorp/setup-packer@v3

    - name: Validate Packer template
      run: packer validate packer/ubuntu-cis.pkr.hcl

    - name: Build CIS-hardened AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        packer build -color=false packer/ubuntu-cis.pkr.hcl

